# Generated by Django 4.2.23 on 2025-08-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('search_parameters', models.JSONField()),
                ('serpapi_search_id', models.CharField(max_length=100)),
                ('platform_request_url', models.URLField()),
                ('raw_response', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_results', models.IntegerField(blank=True, null=True)),
                ('search_at', models.DateTimeField(auto_now_add=True)),
                ('next_page_token', models.TextField(blank=True, null=True)),
                ('next_page_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'search_history',
                'ordering': ['-search_at'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_id', models.CharField(max_length=100)),
                ('advertiser_name', models.CharField(max_length=255)),
                ('ad_creative_id', models.CharField(max_length=100, unique=True)),
                ('ad_format', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('image_url', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('details_link', models.URLField()),
                ('is_selected', models.BooleanField(default=False)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('search_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='search.searchhistory')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'ads',
                'ordering': ['-retrieved_at'],
            },
        ),
    ]
