# Generated by Django 5.2.6 on 2025-09-30 07:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Summary of plan features and intended use cases')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly subscription price in billing currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_users', models.IntegerField(help_text='Maximum team members allowed under this plan', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_storage_gb', models.IntegerField(help_text='Maximum storage allocation in gigabytes', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace plan',
                'verbose_name_plural': 'Workspace plans',
                'db_table': 'billing_workspace_plan',
                'ordering': ['monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TokenAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0, help_text='Current available token balance', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Owning user when the account is tied to an individual', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_account', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(blank=True, help_text='Owning workspace when the account is shared across a team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_account', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Token account',
                'verbose_name_plural': 'Token accounts',
                'db_table': 'billing_token_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Signed token amount; positive for credits, negative for debits')),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('CONSUME', 'Consume'), ('ADJUSTMENT', 'Adjustment')], help_text='Categorisation of the token movement', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional human-readable context for the transaction')),
                ('stripe_payment_id', models.CharField(blank=True, help_text='Stripe payment intent/session identifier when applicable', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Token account affected by this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.tokenaccount')),
            ],
            options={
                'verbose_name': 'Token transaction',
                'verbose_name_plural': 'Token transactions',
                'db_table': 'billing_token_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID (empty for free plan)', max_length=200, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete')], default='active', help_text='Subscription status', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start time of the current billing cycle', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End time of the current billing cycle', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='Trial end time', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Subscription cancellation time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('plan', models.ForeignKey(help_text='Current plan in use', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.workspaceplan')),
                ('workspace', models.OneToOneField(help_text='Associated workspace', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('change', 'Change')], help_text='Type of change', max_length=20)),
                ('effective_timing', models.CharField(choices=[('immediate', 'Immediate'), ('end_of_period', 'End of Period')], default='immediate', help_text='When the change takes effect', max_length=20)),
                ('effective_date', models.DateTimeField(blank=True, help_text='Effective date of the plan change', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', help_text='Processing status', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_plan_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='User who submitted the request', on_delete=django.db.models.deletion.PROTECT, related_name='plan_change_requests', to=settings.AUTH_USER_MODEL)),
                ('from_plan', models.ForeignKey(help_text='Original plan', on_delete=django.db.models.deletion.PROTECT, related_name='downgrade_requests', to='billing.workspaceplan')),
                ('to_plan', models.ForeignKey(help_text='Target plan', on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_requests', to='billing.workspaceplan')),
                ('subscription', models.ForeignKey(help_text='Associated subscription', on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='billing.workspacesubscription')),
            ],
            options={
                'verbose_name': 'Plan Change Request',
                'verbose_name_plural': 'Plan Change Requests',
                'db_table': 'billing_plan_change_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tokenaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('workspace__isnull', True)), models.Q(('user__isnull', True), ('workspace__isnull', False)), _connector='OR'), name='token_account_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='tokenaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='token_account_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tokentransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='token_transaction_non_zero'),
        ),
    ]
