# Generated by Django 5.2.6 on 2025-10-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_token_transaction_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook event log',
                'verbose_name_plural': 'Webhook event logs',
                'db_table': 'billing_webhook_event_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='tokentransaction',
            name='account',
            field=models.ForeignKey(help_text='Token account affected by this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.tokenaccount'),
        ),
    ]
