# Generated by Django 5.2.6 on 2025-10-20 00:02

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_credit_ledger_and_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingauditlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billingeventdeadletter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='currency',
            field=models.CharField(default=billing.models._default_currency, help_text='ISO-4217 currency code for the account balance.', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Associated Stripe customer identifier, if available.', max_length=255, null=True, unique=True),
        ),
    ]
