# Generated by Django 5.2.6 on 2025-10-24 03:41

import billing.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billing_records'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billingtransaction',
            name='billing_tx_single_ledger_source',
        ),
        migrations.AlterField(
            model_name='billingidempotencykey',
            name='request_hash',
            field=models.CharField(help_text='Hash of method, path, and canonical payload.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Absolute monetary value recorded for the transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete marker for archival workflows.', null=True),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='category',
            field=models.CharField(choices=[('token_purchase', 'Token Purchase'), ('token_consume', 'Token Consumption'), ('subscription_invoice', 'Subscription Invoice'), ('credit_adjustment', 'Credit Adjustment'), ('payment', 'Payment'), ('refund', 'Refund'), ('manual', 'Manual Adjustment')], help_text='Classification of the transaction.', max_length=40),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='credit_transaction',
            field=models.OneToOneField(blank=True, help_text='Linked credit transaction when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_entry', to='billing.credittransaction'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='currency',
            field=models.CharField(default=billing.models._default_currency, help_text='ISO-4217 currency code (lowercase).', max_length=3),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='direction',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], help_text='Indicates whether the transaction credits or debits the balance.', max_length=10),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='invoice',
            field=models.OneToOneField(blank=True, help_text='Linked invoice record when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transaction', to='billing.invoicerecord'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='occurred_at',
            field=models.DateTimeField(help_text='When the underlying financial event took place.'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Linked payment record when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transaction', to='billing.paymentrecord'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='refund',
            field=models.OneToOneField(blank=True, help_text='Linked refund record when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transaction', to='billing.refundrecord'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('pending', 'Pending'), ('void', 'Void')], default='posted', help_text='Posting status for reconciliation purposes.', max_length=12),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='token_transaction',
            field=models.OneToOneField(blank=True, help_text='Linked token transaction when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_entry', to='billing.tokentransaction'),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User responsible for the transaction when scoped to individuals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingtransaction',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace that owns the transaction when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='workspace.workspace'),
        ),
        migrations.AddConstraint(
            model_name='billingtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('credit_transaction__isnull', False), ('token_transaction__isnull', False), _negated=True), name='billing_tx_single_ledger_source'),
        ),
    ]
