# Generated by Django 5.2.6 on 2025-10-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_billingtransaction_billing_tx_single_ledger_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesubscription',
            name='auto_renew_enabled',
            field=models.BooleanField(default=False, help_text='Whether the subscription should renew automatically.'),
        ),
    ]
