# Generated by Django 5.2.6 on 2025-09-28 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdSpark', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_title', models.CharField(max_length=1000)),
                ('variant_description', models.TextField()),
                ('variant_image_url', models.URLField(max_length=1000)),
                ('ai_generation_params', models.JSONField()),
                ('ai_agent_platform', models.CharField(max_length=50)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_prompt_used', models.TextField()),
                ('ai_response_metadata', models.JSONField()),
                ('generation_requested_at', models.DateTimeField(auto_now_add=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('original_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='AdSpark.creative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_variants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Variant',
                'verbose_name_plural': 'Ad Variants',
                'db_table': 'ad_variants',
                'ordering': ['-generation_requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AdVariantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('feedback_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai_agent.advariant')),
            ],
            options={
                'verbose_name': 'Ad Variant Feedback',
                'verbose_name_plural': 'Ad Variant Feedbacks',
                'db_table': 'ad_variant_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('variant', 'user')},
            },
        ),
    ]
