# Generated by Django 5.2.6 on 2025-10-11 11:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdSpark', '0002_initial'),
        ('ai_agent', '0001_initial'),
        ('billing', '0003_webhookeventlog_alter_tokentransaction_account'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advariant',
            name='token_transaction',
            field=models.ForeignKey(blank=True, help_text='Token consumption transaction associated with this generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_variants', to='billing.tokentransaction'),
        ),
        migrations.CreateModel(
            name='WorkspaceAdVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_title', models.CharField(max_length=1000)),
                ('variant_description', models.TextField()),
                ('variant_image_url', models.URLField(max_length=1000)),
                ('ai_generation_params', models.JSONField()),
                ('ai_agent_platform', models.CharField(max_length=50)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_prompt_used', models.TextField()),
                ('ai_response_metadata', models.JSONField()),
                ('generation_requested_at', models.DateTimeField(auto_now_add=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('original_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_variants', to='AdSpark.creative')),
                ('token_transaction', models.ForeignKey(blank=True, help_text='Token transaction recorded for this workspace generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_ad_variants', to='billing.tokentransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_ad_variants', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_ad_variants', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_ad_variants',
                'ordering': ['-generation_requested_at'],
            },
        ),
    ]
