"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-4g=$b1l14w5*aia@bgix6zv9%ky2#elk0f*jso867wpgcq8&3u')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Allow ngrok domains for development (*.ngrok-free.dev, *.ngrok.io)
# In production, set ALLOWED_HOSTS env var to specific domains
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,0.0.0.0,.ngrok-free.dev,.ngrok.io'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'django_celery_beat',
    'test_app',
    #'campaigns',
    'django_extensions',
    'accounts',
    'ai_agent',
    'rest_framework.authtoken',
    'AdSpark',
    'workspace',
    'assets',
    'search.apps.SearchConfig',
    'channels',
    'billing',
    'audit.apps.AuditConfig',
    'template_library',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection enabled
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.ApiAuditMiddleware',
    'billing.middleware.idempotency.BillingIdempotencyMiddleware',
]
APPEND_SLASH = False

CSRF_TRUSTED_ORIGINS  = [
    "http://localhost:3000",
    "http://localhost",
    "http://127.0.0.1:3000",
    "http://localhost:80",
    "http://127.0.0.1:80",
    "https://adulterously-uncatechized-salma.ngrok-free.dev",
    "https://noumenal-tom-milkily.ngrok-free.dev",
    "https://delcie-unobsequious-superindifferently.ngrok-free.dev",
    "https://pregranitic-undeprecatingly-kayce.ngrok-free.dev",
]


#CORS Setting
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost",
    "http://127.0.0.1:3000",
    "http://localhost:80",
    "http://127.0.0.1:80",
    "https://adulterously-uncatechized-salma.ngrok-free.dev",
    "https://noumenal-tom-milkily.ngrok-free.dev",
    "https://delcie-unobsequious-superindifferently.ngrok-free.dev",
    "https://pregranitic-undeprecatingly-kayce.ngrok-free.dev",
]

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
    "origin",
    "user-agent",
    "dnt",
    "cache-control",
    "x-requested-with",
    "x-csrftoken",
    "idempotency-key",  # For billing operations
]

CORS_ALLOW_CREDENTIALS = True   # Essential for cookies/sessions
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB', default='mediajira_db'),
        'USER': config('POSTGRES_USER', default='postgres'),
        'PASSWORD': config('POSTGRES_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('POSTGRES_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Static files configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

#Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST ='smtp.mailersend.net'
EMAIL_PORT =587
EMAIL_HOST_USER ='MS_YmzdHn@test-dnvo4.d90173g5r86.mlsender.net'
EMAIL_HOST_PASSWORD = 'mssp.XOpcXaV.v69oxl5m93z4785k.WVQSpf2'
DEFAULT_FROM_EMAIL = 'MS_YmzdHn@test-dnvo4.d90173g5r86.mlsender.net'
EMAIL_USE_TLS =True

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Celery Broker and Result Backend Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Define the ASGI entrypoint (replaces WSGI for async support)
# This tells Django to use ASGI instead of WSGI for handling requests
ASGI_APPLICATION = "backend.asgi.application"

# Configure Channels to use Redis as the channel layer backend
CHANNEL_LAYERS = {
    "default": {
        # Backend implementation for channel layers
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Redis server connection (host, port)
            "hosts": [("redis", 6379)]
        },
    },
}

# Ensure Logs dir exits
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# LOGGING setting
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'celery.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['celery_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'AdSpark': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'ai_agent': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Stripe Configuration for Token Payments
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
STRIPE_SUCCESS_URL = config('STRIPE_SUCCESS_URL', default='')
STRIPE_CANCEL_URL = config('STRIPE_CANCEL_URL', default='')
STRIPE_WEBHOOK_URL = config('STRIPE_WEBHOOK_URL', default='')
BILLING_PUBLIC_BASE_URL = config('BILLING_PUBLIC_BASE_URL', default='')
WEBHOOK_PUBLIC_URL = config('WEBHOOK_PUBLIC_URL', default='')
STRIPE_CURRENCY = config('STRIPE_CURRENCY', default='aud')

# Token pricing configuration (in AUD)
STRIPE_TOKEN_PRICE_PER_100 = 5.00  # 100 tokens = 5 AUD
DEFAULT_TOKENS_PER_GENERATION = 300

# Stripe Product Configuration
STRIPE_PRODUCT_IDS = {
    'token_topup_1000': 'prod_T8s4p34zh6N76U', #for 1000 token, 9 AUD
    'token_topup_100': 'prod_T9BCcwMmtflvap', # for 100 token, 5 AUD
    'workspace_plans': { # Free: Max user , Max storage 20, 0 AUD per month
        'basic': 'prod_T8rx4pEeTushUy',# Max user 50, Max storage GB 100, 29 AUD per month
        'pro': 'prod_T8sdrP8F8JoPBU',# Max user 200, Max storage GB 500.70 AUD per month
        'enterprise': 'prod_T8sevfvksg5kjz' # Max user 1000, Max storage GB 2000, 249 AUD per month
    }
}

PLAN_CONFIG = {
    'free': {
        'max_users': 10,
        'max_storage_gb': 20,
        'monthly_price': 0,
        'description': 'Free tier with core collaboration features.',
    },
    'basic': {
        'max_users': 50,
        'max_storage_gb': 100,
        'monthly_price': 29,
        'description': 'Basic plan suited for growing teams.',
    },
    'pro': {
        'max_users': 200,
        'max_storage_gb': 500,
        'monthly_price': 70,
        'description': 'Pro plan with advanced collaboration limits.',
    },
    'enterprise': {
        'max_users': 1000,
        'max_storage_gb': 2000,
        'monthly_price': 249,
        'description': 'Enterprise plan with the highest scale and support.',
    },
}

# Test database configuration - Use SQLite for testing when PostgreSQL is unavailable
import sys
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'test_db.sqlite3',
        }
    }

# =============================================================================
# Session and Cookie Configuration
# =============================================================================

# Session Configuration
SESSION_COOKIE_HTTPONLY = True    # Prevent JavaScript access (security)
SESSION_COOKIE_NAME = 'sessionid' # Default name
SESSION_COOKIE_DOMAIN = None      # Auto-bind to current domain (ngrok or localhost)

# CSRF Configuration
CSRF_COOKIE_HTTPONLY = False      # Allow JavaScript to read CSRF token
CSRF_COOKIE_NAME = 'csrftoken'    # Default name
CSRF_COOKIE_DOMAIN = None         # Auto-bind to current domain
CSRF_USE_SESSIONS = False         # Use cookie-based CSRF (not session-based)

# Environment-specific settings
if DEBUG:
    # Development: Support both localhost (HTTP) and ngrok (HTTPS)
    # SameSite=Lax is the recommended default (provides CSRF protection)
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False  # Django runs on HTTP inside Docker
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False     # Django runs on HTTP inside Docker

    # Note: Even though backend is HTTP, nginx/ngrok handle HTTPS externally
    # Cookies will still be transmitted securely over HTTPS from browser to nginx
else:
    # Production: Standard secure settings
    SESSION_COOKIE_SAMESITE = 'Lax'   # Recommended for CSRF protection
    SESSION_COOKIE_SECURE = True      # Require HTTPS
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True






