# Generated by Django 5.2.6 on 2025-09-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('advertiser_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'db_table': 'adspark_advertiser',
            },
        ),
        migrations.CreateModel(
            name='Google_Ads_GeoId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_id', models.IntegerField(unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('tld', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('advertiser_ids', models.TextField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=8, null=True)),
                ('platform', models.CharField(blank=True, max_length=16, null=True)),
                ('creative_format', models.CharField(blank=True, max_length=16, null=True)),
                ('political_ads', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watches',
                'db_table': 'adspark_watch',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('ad_creative_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=16)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('video_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('target_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('first_shown', models.DateTimeField(db_index=True)),
                ('last_shown', models.DateTimeField(db_index=True)),
                ('details_link', models.URLField(max_length=1000)),
                ('region', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PLAY', 'Google Play'), ('MAPS', 'Google Maps'), ('SEARCH', 'Google Search'), ('SHOPPING', 'Google Shopping'), ('YOUTUBE', 'YouTube')], max_length=16, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='AdSpark.advertiser')),
            ],
            options={
                'verbose_name': 'Creative',
                'verbose_name_plural': 'Creatives',
                'db_table': 'adspark_creative',
            },
        ),
    ]
