# Generated by Django 5.2.6 on 2025-09-29 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdSpark', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creative',
            index=models.Index(fields=['advertiser', 'format', 'region'], name='adspark_cre_adverti_acc0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='creative',
            index=models.Index(fields=['target_domain'], name='adspark_cre_target__995d55_idx'),
        ),
        migrations.AddIndex(
            model_name='creative',
            index=models.Index(fields=['platform', 'format'], name='adspark_cre_platfor_7be3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='creative',
            index=models.Index(fields=['first_shown', 'last_shown'], name='adspark_cre_first_s_91c342_idx'),
        ),
    ]
