# Generated by Django 5.2.6 on 2025-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdSpark', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
