# Generated by Django 5.2.6 on 2025-11-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdSpark', '0003_creative_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreativeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_titles', to='AdSpark.creative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Creative Title',
                'verbose_name_plural': 'User Creative Titles',
                'db_table': 'adspark_user_creative_title',
                'indexes': [models.Index(fields=['user', 'creative'], name='adspark_use_user_id_09d522_idx')],
                'unique_together': {('user', 'creative')},
            },
        ),
    ]
