# Generated by Django 5.2.6 on 2025-09-29 23:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the invitation link', primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token embedded in invitation URL for security', unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Role that will be automatically assigned to users joining via this link', max_length=20)),
                ('name', models.CharField(help_text='Human-readable name for this invitation link', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description explaining the purpose of this invitation link', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this invitation link expires (null means never expires)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this invitation link is currently active and usable')),
                ('max_uses', models.IntegerField(default=1000, help_text='Maximum number of times this link can be used (null means unlimited)', validators=[django.core.validators.MinValueValidator(1)])),
                ('uses_count', models.IntegerField(default=0, help_text='Current number of times this link has been successfully used', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this invitation link was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this invitation link was last modified')),
                ('creator_notes', models.TextField(blank=True, help_text='Private notes from the creator about this invitation link', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this invitation link', on_delete=django.db.models.deletion.CASCADE, related_name='created_invitation_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Invitation Link',
                'verbose_name_plural': 'Workspace Invitation Links',
                'db_table': 'workspace_invitation_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the workspace', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Workspace name for identification', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description explaining workspace purpose', null=True)),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('pro', 'Professional Plan'), ('enterprise', 'Enterprise Plan')], default='free', help_text='Subscription plan determining feature access and limits', max_length=50)),
                ('max_users', models.IntegerField(default=10, help_text='Maximum number of users allowed in this workspace', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('max_storage_gb', models.IntegerField(default=20, help_text='Maximum storage capacity in GB for assets and files', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether workspace is active and accessible to members')),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='When workspace was created')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional expiration date for temporary workspaces', null=True)),
                ('workspace_type', models.CharField(choices=[('standard', 'Standard Workspace'), ('demo', 'Demo/Trial Workspace'), ('enterprise', 'Enterprise Workspace')], default='standard', help_text='Type of workspace affecting available features', max_length=20)),
                ('api_keys', models.JSONField(blank=True, default=dict, help_text='Storage for various API keys and external service configurations', null=True)),
                ('serpapi_key', models.CharField(blank=True, help_text='SerpAPI key for fetching Google Ads Transparency Center data', max_length=200, null=True)),
                ('serpapi_config', models.JSONField(blank=True, default=dict, help_text='SerpAPI configuration including default regions, filters, and preferences', null=True)),
                ('tags', models.JSONField(blank=True, default=dict, help_text='Flexible metadata storage for workspace categorization and settings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of workspace creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last workspace modification')),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who created and owns this workspace - has all permissions', on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspace',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], help_text='Role determining user permissions within the workspace', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the user was first added to the workspace')),
                ('invitation_accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted (null for direct additions)', null=True)),
                ('custom_permissions', models.JSONField(blank=True, default=dict, help_text='Fine-grained permissions override for specific capabilities')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who sent the workspace invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who is a member of the workspace', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Membership',
                'verbose_name_plural': 'Workspace Memberships',
                'db_table': 'workspace_membership',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user successfully joined the workspace')),
                ('assigned_role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], help_text='Role that was assigned to the user upon joining', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Successfully Joined'), ('already_member', 'Already a Member'), ('link_expired', 'Link Expired'), ('link_invalid', 'Link Invalid'), ('workspace_full', 'Workspace at Capacity'), ('permission_denied', 'Permission Denied'), ('error', 'System Error')], default='success', help_text='Result status of the join attempt', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user when joining (for security auditing)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string (for analytics and debugging)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or error details about this join event', null=True)),
                ('invitation_link', models.ForeignKey(help_text='Invitation link that was used for this join event', on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='workspace.invitationlink')),
                ('user', models.ForeignKey(help_text='User who joined the workspace via the invitation link', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_usage_history', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, help_text='Membership record created as a result of this invitation (if successful)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_source', to='workspace.membership')),
                ('workspace', models.ForeignKey(help_text='Workspace that the user joined', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_join_history', to='workspace.workspace')),
            ],
            options={
                'verbose_name': 'Invitation Usage Record',
                'verbose_name_plural': 'Invitation Usage Records',
                'db_table': 'workspace_invitation_usage',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='invitationlink',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace that users will join when using this invitation link', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='workspace.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspacePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_library', models.BooleanField(default=True, help_text='Permission to view workspace creative library and collections')),
                ('can_upload_assets', models.BooleanField(default=True, help_text='Permission to upload images, videos, and other assets')),
                ('can_generate_variants', models.BooleanField(default=True, help_text='Permission to create AI-generated creative variants')),
                ('can_edit_variants', models.BooleanField(default=False, help_text='Permission to modify existing creative variants')),
                ('can_approve_variants', models.BooleanField(default=False, help_text='Permission to approve variants for publication/export')),
                ('can_export_data', models.BooleanField(default=True, help_text='Permission to export creatives and data from workspace')),
                ('can_view_billing', models.BooleanField(default=False, help_text='Permission to view billing information and usage statistics')),
                ('can_manage_billing', models.BooleanField(default=False, help_text='Permission to manage payments and billing settings')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Permission to invite, remove, and manage other workspace members')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Permission to modify workspace settings and configuration')),
                ('can_view_audit_logs', models.BooleanField(default=False, help_text='Permission to access audit logs and activity history')),
                ('max_upload_size_mb', models.IntegerField(default=100, help_text='Maximum file upload size in MB for this user', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('max_monthly_jobs', models.IntegerField(default=50, help_text='Maximum number of generation jobs per month', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('can_delete_workspace', models.BooleanField(default=False, help_text='Permission to delete the workspace')),
                ('can_transfer_ownership', models.BooleanField(default=False, help_text='Permission to transfer workspace ownership')),
                ('can_manage_invitations', models.BooleanField(default=False, help_text='Permission to create, update, and deactivate invitation links')),
                ('can_update_token_balance', models.BooleanField(default=False, help_text='Permission to update the token balance of the workspace')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When these permissions were first assigned')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these permissions were last modified')),
                ('membership', models.OneToOneField(help_text='The membership this permission record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='workspace.membership')),
            ],
            options={
                'verbose_name': 'Workspace Permission',
                'verbose_name_plural': 'Workspace Permissions',
                'db_table': 'workspace_permission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'is_active'], name='workspace_owner_i_b8c330_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['plan', 'workspace_type'], name='workspace_plan_9696fd_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_at'], name='workspace_created_883e60_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'role', 'is_active'], name='workspace_m_workspa_ad72c0_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='workspace_m_user_id_0032f2_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['invited_by'], name='workspace_m_invited_dbb3db_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('workspace',), name='unique_workspace_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('workspace', 'user')},
        ),
        migrations.AddIndex(
            model_name='invitationusage',
            index=models.Index(fields=['invitation_link', 'status'], name='workspace_i_invitat_13c59d_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationusage',
            index=models.Index(fields=['user', 'joined_at'], name='workspace_i_user_id_b02be0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationusage',
            index=models.Index(fields=['workspace', 'joined_at'], name='workspace_i_workspa_c045c5_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationusage',
            index=models.Index(fields=['joined_at'], name='workspace_i_joined__fa0713_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitationusage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('invitation_link', 'user'), name='unique_successful_invitation_usage'),
        ),
        migrations.AddIndex(
            model_name='invitationlink',
            index=models.Index(fields=['token'], name='workspace_i_token_d8fcfb_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationlink',
            index=models.Index(fields=['workspace', 'is_active'], name='workspace_i_workspa_5045f0_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationlink',
            index=models.Index(fields=['created_by'], name='workspace_i_created_7c57cb_idx'),
        ),
        migrations.AddIndex(
            model_name='invitationlink',
            index=models.Index(fields=['expires_at', 'is_active'], name='workspace_i_expires_2b291d_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitationlink',
            constraint=models.UniqueConstraint(fields=('token',), name='unique_invitation_token'),
        ),
        migrations.AddConstraint(
            model_name='workspacepermission',
            constraint=models.UniqueConstraint(fields=('membership',), name='unique_workspace_permission_membership'),
        ),
    ]
