from django.apps import AppConfig
from django.db.models.signals import post_migrate


class AdsparkConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'AdSpark'

    def ready(self):
        """
        After migrations are applied, ensure Google_Ads_GeoId data exists.
        """
        from django.db import connections, router
        from django.db.utils import OperationalError, ProgrammingError

        def ensure_google_ads_geoid(sender, **kwargs):
            from .models import Google_Ads_GeoId  # 延迟导入，避免循环引用

            GEO_DATA = [
                (2004, 'Afghanistan', 'AF', '.af'),
                (2008, 'Albania', 'AL', '.al'),
                (2012, 'Algeria', 'DZ', '.dz'),
                (2016, 'American Samoa', 'AS', '.as'),
                (2020, 'Andorra', 'AD', '.ad'),
                (2024, 'Angola', 'AO', '.ao'),
                (2010, 'Antarctica', 'AQ', '.aq'),
                (2028, 'Antigua and Barbuda', 'AG', '.ag'),
                (2032, 'Argentina', 'AR', '.ar'),
                (2051, 'Armenia', 'AM', '.am'),
                (2036, 'Australia', 'AU', '.au'),
                (2040, 'Austria', 'AT', '.at'),
                (2031, 'Azerbaijan', 'AZ', '.az'),
                (2048, 'Bahrain', 'BH', '.bh'),
                (2050, 'Bangladesh', 'BD', '.bd'),
                (2052, 'Barbados', 'BB', '.bb'),
                (2112, 'Belarus', 'BY', '.by'),
                (2056, 'Belgium', 'BE', '.be'),
                (2084, 'Belize', 'BZ', '.bz'),
                (2204, 'Benin', 'BJ', '.bj'),
                (2064, 'Bhutan', 'BT', '.bt'),
                (2068, 'Bolivia', 'BO', '.bo'),
                (2070, 'Bosnia and Herzegovina', 'BA', '.ba'),
                (2072, 'Botswana', 'BW', '.bw'),
                (2076, 'Brazil', 'BR', '.br'),
                (2096, 'Brunei', 'BN', '.bn'),
                (2100, 'Bulgaria', 'BG', '.bg'),
                (2854, 'Burkina Faso', 'BF', '.bf'),
                (2108, 'Burundi', 'BI', '.bi'),
                (2116, 'Cambodia', 'KH', '.kh'),
                (2120, 'Cameroon', 'CM', '.cm'),
                (2124, 'Canada', 'CA', '.ca'),
                (2132, 'Cape Verde', 'CV', '.cv'),
                (2535, 'Caribbean Netherlands', 'BQ', '.bq'),
                (2140, 'Central African Republic', 'CF', '.cf'),
                (2148, 'Chad', 'TD', '.td'),
                (2152, 'Chile', 'CL', '.cl'),
                (2156, 'China', 'CN', '.cn'),
                (2162, 'Christmas Island', 'CX', '.cx'),
                (2166, 'Cocos (Keeling) Islands', 'CC', '.cc'),
                (2170, 'Colombia', 'CO', '.co'),
                (2174, 'Comoros', 'KM', '.km'),
                (2184, 'Cook Islands', 'CK', '.ck'),
                (2188, 'Costa Rica', 'CR', '.cr'),
                (2384, 'Cote d\'Ivoire', 'CI', '.ci'),
                (2191, 'Croatia', 'HR', '.hr'),
                (2531, 'Curacao', 'CW', '.cw'),
                (2196, 'Cyprus', 'CY', '.cy'),
                (2203, 'Czechia', 'CZ', '.cz'),
                (2180, 'Democratic Republic of the Congo', 'CD', '.cd'),
                (2208, 'Denmark', 'DK', '.dk'),
                (2262, 'Djibouti', 'DJ', '.dj'),
                (2212, 'Dominica', 'DM', '.dm'),
                (2214, 'Dominican Republic', 'DO', '.do'),
                (2218, 'Ecuador', 'EC', '.ec'),
                (2818, 'Egypt', 'EG', '.eg'),
                (2222, 'El Salvador', 'SV', '.sv'),
                (2226, 'Equatorial Guinea', 'GQ', '.gq'),
                (2232, 'Eritrea', 'ER', '.er'),
                (2233, 'Estonia', 'EE', '.ee'),
                (2748, 'Eswatini', 'SZ', '.sz'),
                (2231, 'Ethiopia', 'ET', '.et'),
                (2583, 'Federated States of Micronesia', 'FM', '.fm'),
                (2242, 'Fiji', 'FJ', '.fj'),
                (2246, 'Finland', 'FI', '.fi'),
                (2250, 'France', 'FR', '.fr'),
                (2258, 'French Polynesia', 'PF', '.pf'),
                (2260, 'French Southern and Antarctic Lands', 'TF', '.tf'),
                (2266, 'Gabon', 'GA', '.ga'),
                (2268, 'Georgia', 'GE', '.ge'),
                (2276, 'Germany', 'DE', '.de'),
                (2288, 'Ghana', 'GH', '.gh'),
                (2300, 'Greece', 'GR', '.gr'),
                (2308, 'Grenada', 'GD', '.gd'),
                (2316, 'Guam', 'GU', '.gu'),
                (2320, 'Guatemala', 'GT', '.gt'),
                (2831, 'Guernsey', 'GG', '.gg'),
                (2324, 'Guinea', 'GN', '.gn'),
                (2624, 'Guinea-Bissau', 'GW', '.gw'),
                (2328, 'Guyana', 'GY', '.gy'),
                (2332, 'Haiti', 'HT', '.ht'),
                (2334, 'Heard Island and McDonald Islands', 'HM', '.hm'),
                (2340, 'Honduras', 'HN', '.hn'),
                (2348, 'Hungary', 'HU', '.hu'),
                (2352, 'Iceland', 'IS', '.is'),
                (2356, 'India', 'IN', '.in'),
                (2360, 'Indonesia', 'ID', '.id'),
                (2368, 'Iraq', 'IQ', '.iq'),
                (2372, 'Ireland', 'IE', '.ie'),
                (2376, 'Israel', 'IL', '.il'),
                (2380, 'Italy', 'IT', '.it'),
                (2388, 'Jamaica', 'JM', '.jm'),
                (2392, 'Japan', 'JP', '.jp'),
                (2832, 'Jersey', 'JE', '.je'),
                (2400, 'Jordan', 'JO', '.jo'),
                (2398, 'Kazakhstan', 'KZ', '.kz'),
                (2404, 'Kenya', 'KE', '.ke'),
                (2296, 'Kiribati', 'KI', '.ki'),
                (2414, 'Kuwait', 'KW', '.kw'),
                (2417, 'Kyrgyzstan', 'KG', '.kg'),
                (2418, 'Laos', 'LA', '.la'),
                (2428, 'Latvia', 'LV', '.lv'),
                (2422, 'Lebanon', 'LB', '.lb'),
                (2426, 'Lesotho', 'LS', '.ls'),
                (2430, 'Liberia', 'LR', '.lr'),
                (2434, 'Libya', 'LY', '.ly'),
                (2438, 'Liechtenstein', 'LI', '.li'),
                (2440, 'Lithuania', 'LT', '.lt'),
                (2442, 'Luxembourg', 'LU', '.lu'),
                (2450, 'Madagascar', 'MG', '.mg'),
                (2454, 'Malawi', 'MW', '.mw'),
                (2458, 'Malaysia', 'MY', '.my'),
                (2462, 'Maldives', 'MV', '.mv'),
                (2466, 'Mali', 'ML', '.ml'),
                (2470, 'Malta', 'MT', '.mt'),
                (2584, 'Marshall Islands', 'MH', '.mh'),
                (2478, 'Mauritania', 'MR', '.mr'),
                (2480, 'Mauritius', 'MU', '.mu'),
                (2484, 'Mexico', 'MX', '.mx'),
                (2498, 'Moldova', 'MD', '.md'),
                (2492, 'Monaco', 'MC', '.mc'),
                (2496, 'Mongolia', 'MN', '.mn'),
                (2499, 'Montenegro', 'ME', '.me'),
                (2504, 'Morocco', 'MA', '.ma'),
                (2508, 'Mozambique', 'MZ', '.mz'),
                (2104, 'Myanmar (Burma)', 'MM', '.mm'),
                (2516, 'Namibia', 'NA', '.na'),
                (2520, 'Nauru', 'NR', '.nr'),
                (2524, 'Nepal', 'NP', '.np'),
                (2528, 'Netherlands', 'NL', '.nl'),
                (2540, 'New Caledonia', 'NC', '.nc'),
                (2554, 'New Zealand', 'NZ', '.nz'),
                (2558, 'Nicaragua', 'NI', '.ni'),
                (2562, 'Niger', 'NE', '.ne'),
                (2566, 'Nigeria', 'NG', '.ng'),
                (2570, 'Niue', 'NU', '.nu'),
                (2574, 'Norfolk Island', 'NF', '.nf'),
                (2807, 'North Macedonia', 'MK', '.mk'),
                (2580, 'Northern Mariana Islands', 'MP', '.mp'),
                (2578, 'Norway', 'NO', '.no'),
                (2512, 'Oman', 'OM', '.om'),
                (2586, 'Pakistan', 'PK', '.pk'),
                (2585, 'Palau', 'PW', '.pw'),
                (2591, 'Panama', 'PA', '.pa'),
                (2598, 'Papua New Guinea', 'PG', '.pg'),
                (2600, 'Paraguay', 'PY', '.py'),
                (2604, 'Peru', 'PE', '.pe'),
                (2608, 'Philippines', 'PH', '.ph'),
                (2612, 'Pitcairn Islands', 'PN', '.pn'),
                (2616, 'Poland', 'PL', '.pl'),
                (2620, 'Portugal', 'PT', '.pt'),
                (2634, 'Qatar', 'QA', '.qa'),
                (2178, 'Republic of the Congo', 'CG', '.cg'),
                (2642, 'Romania', 'RO', '.ro'),
                (2643, 'Russia', 'RU', '.ru'),
                (2646, 'Rwanda', 'RW', '.rw'),
                (2652, 'Saint Barthelemy', 'BL', '.bl'),
                (2654, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', '.sh'),
                (2659, 'Saint Kitts and Nevis', 'KN', '.kn'),
                (2662, 'Saint Lucia', 'LC', '.lc'),
                (2663, 'Saint Martin', 'MF', '.mf'),
                (2666, 'Saint Pierre and Miquelon', 'PM', '.pm'),
                (2670, 'Saint Vincent and the Grenadines', 'VC', '.vc'),
                (2882, 'Samoa', 'WS', '.ws'),
                (2674, 'San Marino', 'SM', '.sm'),
                (2678, 'Sao Tome and Principe', 'ST', '.st'),
                (2682, 'Saudi Arabia', 'SA', '.sa'),
                (2686, 'Senegal', 'SN', '.sn'),
                (2688, 'Serbia', 'RS', '.rs'),
                (2690, 'Seychelles', 'SC', '.sc'),
                (2694, 'Sierra Leone', 'SL', '.sl'),
                (2702, 'Singapore', 'SG', '.sg'),
                (2534, 'Sint Maarten', 'SX', '.sx'),
                (2703, 'Slovakia', 'SK', '.sk'),
                (2705, 'Slovenia', 'SI', '.si'),
                (2090, 'Solomon Islands', 'SB', '.sb'),
                (2706, 'Somalia', 'SO', '.so'),
                (2710, 'South Africa', 'ZA', '.za'),
                (2239, 'South Georgia and the South Sandwich Islands', 'GS', '.gs'),
                (2410, 'South Korea', 'KR', '.kr'),
                (2728, 'South Sudan', 'SS', '.ss'),
                (2724, 'Spain', 'ES', '.es'),
                (2144, 'Sri Lanka', 'LK', '.lk'),
                (2736, 'Sudan', 'SD', '.sd'),
                (2740, 'Suriname', 'SR', '.sr'),
                (2752, 'Sweden', 'SE', '.se'),
                (2756, 'Switzerland', 'CH', '.ch'),
                (2158, 'Taiwan', 'TW', '.tw'),
                (2762, 'Tajikistan', 'TJ', '.tj'),
                (2834, 'Tanzania', 'TZ', '.tz'),
                (2764, 'Thailand', 'TH', '.th'),
                (2044, 'The Bahamas', 'BS', '.bs'),
                (2270, 'The Gambia', 'GM', '.gm'),
                (2626, 'Timor-Leste', 'TL', '.tl'),
                (2768, 'Togo', 'TG', '.tg'),
                (2772, 'Tokelau', 'TK', '.tk'),
                (2776, 'Tonga', 'TO', '.to'),
                (2780, 'Trinidad and Tobago', 'TT', '.tt'),
                (2788, 'Tunisia', 'TN', '.tn'),
                (2792, 'Turkey', 'TR', '.tr'),
                (2795, 'Turkmenistan', 'TM', '.tm'),
                (2798, 'Tuvalu', 'TV', '.tv'),
                (2800, 'Uganda', 'UG', '.ug'),
                (2804, 'Ukraine', 'UA', '.ua'),
                (2784, 'United Arab Emirates', 'AE', '.ae'),
                (2826, 'United Kingdom', 'GB', '.uk'),
                (2840, 'United States', 'US', '.us'),
                (2581, 'United States Minor Outlying Islands', 'UM', '.um'),
                (2858, 'Uruguay', 'UY', '.uy'),
                (2860, 'Uzbekistan', 'UZ', '.uz'),
                (2548, 'Vanuatu', 'VU', '.vu'),
                (2336, 'Vatican City', 'VA', '.va'),
                (2862, 'Venezuela', 'VE', '.ve'),
                (2704, 'Vietnam', 'VN', '.vn'),
                (2876, 'Wallis and Futuna', 'WF', '.wf'),
                (2887, 'Yemen', 'YE', '.ye'),
                (2894, 'Zambia', 'ZM', '.zm'),
                (2716, 'Zimbabwe', 'ZW', '.zw'),
            ]

            try:
                for geo_id, country_name, country_code, tld in GEO_DATA:
                    if not Google_Ads_GeoId.objects.filter(geo_id=geo_id).exists():
                        Google_Ads_GeoId.objects.create(
                            geo_id=geo_id,
                            country_name=country_name,
                            country_code=country_code,
                            tld=tld
                        )
            except (OperationalError, ProgrammingError):
                # 数据库表可能还没创建（第一次 migrate 时），跳过
                pass

        post_migrate.connect(ensure_google_ads_geoid, sender=self)
