# Generated by Django 5.2.6 on 2025-10-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiaccesslog',
            new_name='audit_api_a_user_id_5d133c_idx',
            old_name='audit_log_user_ts',
        ),
        migrations.RenameIndex(
            model_name='apiaccesslog',
            new_name='audit_api_a_action_e0ff3f_idx',
            old_name='audit_log_action_ts',
        ),
        migrations.RenameIndex(
            model_name='apiaccesslog',
            new_name='audit_api_a_status__6b4966_idx',
            old_name='audit_log_status_ts',
        ),
    ]
